version: '3'
services:
#  server:
#    build: .
#    image: server:v0
#    ports:
#      - 9090:9090
#    depends_on:
#      - etcd
  # Docker: https://hub.docker.com/r/bitnami/etcd/
  # Compose: https://github.com/bitnami/bitnami-docker-etcd/
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./etcd-data:/bitnami/etcd
    expose:
      - 2379
      - 2380
    ports:
      - 2379:2379
      - 2380:2380
